# Generated by Django 3.0 on 2022-01-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieForfait',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie_forfait', models.CharField(max_length=100)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=125)),
                ('num_armoire', models.CharField(max_length=125)),
                ('adresse1', models.TextField(blank=True, null=True)),
                ('adresse2', models.TextField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('tel', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flux', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=75, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revendeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatutTache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_echange', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_prestation', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('date_programmee', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('temps_passe', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
                ('personnes_en_charge', models.ManyToManyField(blank=True, null=True, to='dashboard.Intervenant')),
                ('statut', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.StatutTache')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_programmee', models.DateField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
                ('intervenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Intervenant')),
                ('statut', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.StatutTache')),
                ('type_prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.TypePrestation')),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField()),
                ('categorie_forfait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.CategorieForfait')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Contact')),
                ('statut', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.StatutTache')),
                ('type_echange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.TypeEchange')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('nb_docs', models.IntegerField(blank=True, null=True)),
                ('volume_docs', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='revendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Revendeur'),
        ),
        migrations.AddField(
            model_name='categorieforfait',
            name='flux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Flux'),
        ),
    ]
