# Generated by Django 3.0 on 2022-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echange',
            name='temps_passe',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
