# Generated by Django 3.0 on 2021-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='date_realisation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
