# Generated by Django 3.0 on 2022-02-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_echange_temps_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProjet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_projet', models.CharField(max_length=25)),
                ('icone', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='num_armoire',
        ),
        migrations.RemoveField(
            model_name='client',
            name='revendeur',
        ),
        migrations.RemoveField(
            model_name='consommation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='forfait',
            name='client',
        ),
        migrations.RemoveField(
            model_name='prestation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='client',
        ),
        migrations.AddField(
            model_name='consommation',
            name='forfait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Forfait'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_armoire', models.CharField(blank=True, max_length=125, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Client')),
                ('revendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Revendeur')),
                ('type_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.TypeProjet')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='type_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.TypeProjet'),
        ),
        migrations.AddField(
            model_name='echange',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Projet'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Projet'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Projet'),
        ),
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Projet'),
        ),
    ]
