# Generated by Django 3.0 on 2022-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220214_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='classeurs',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='forfait',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
