# Generated by Django 3.0 on 2022-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220325_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
