# Generated by Django 3.0 on 2022-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220406_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='volume_docs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
