# Generated by Django 3.0 on 2022-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220408_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echange',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
